defmodule Vapor.Quality.Report do
  @moduledoc "The quality benchmark's report: Markdown for people, JSON for machines."
  alias Vapor.Quality.Suite

  @doc "A JSON-safe copy of a report (tuples → lists, non-finite → strings)."
  def plain(%{__struct__: _} = s), do: s |> Map.from_struct() |> plain()
  def plain(m) when is_map(m), do: Map.new(m, fn {k, v} -> {to_string(k), plain(v)} end)
  def plain(l) when is_list(l), do: Enum.map(l, &plain/1)
  def plain(t) when is_tuple(t), do: t |> Tuple.to_list() |> plain()
  def plain(b) when is_binary(b), do: if(String.valid?(b), do: b, else: Base.encode64(b))
  def plain(x), do: x

  def json(report), do: Vapor.JSON.encode(plain(report))

  @doc "The Markdown report."
  def markdown(r) do
    checks = Suite.checks(r)
    passed = Enum.count(checks, & &1.pass)

    """
    # Output quality — vapor

    Generated by `mix vapor.quality` (substrate: **#{r.substrate}**, #{r.timings_ms.total} ms in total).
    **#{passed} of #{length(checks)} checks passed.** Each check compares an output
    with the known truth **and** with a control that a noise generator would reach — passing
    means "signal", and a failure gives the distance. Methodology: [docs/QUALITY.md](../QUALITY.md).

    ## 1. The noise gates, calibrated before judging

    Each gate is fitted to negative controls (noise, shuffled signal, repetition) and
    positive ones (held-out real signal) and **refuses to exist** if they overlap. The margin is the
    gap between the worst negative and the worst positive.

    | gate | score | worst negative | worst positive | margin | controls |
    |---|---|---|---|---|---|
    #{Enum.map_join(r.gates, "\n", fn {name, g} -> "| #{name} | #{dir(g.direction)} | #{f(g.t_noise)} | #{f(g.t_natural)} | #{f(g.margin)} | #{controls(g.controls)} |" end)}

    ## 2. Text: a planted model through the whole stack

    A bigram counted on the Portuguese prose of `docs/`, embedded **exactly** in the weights of a
    Llama decoder (`Vapor.Quality.Planted`), admitted by the airlock, compiled and run.

    | measure | value |
    |---|---|
    | max \\|logit − log P\\| against the analytic table | #{e(r.text.max_table_error)} |
    | bits/character of the model (held out) | #{f(r.text.bits_per_char)} |
    | bits/character of the table | #{f(r.text.table_bits)} |
    | unigram baseline | #{f(r.text.unigram_bits)} |
    | uniform baseline | #{f(r.text.uniform_bits)} |
    | gate verdict, generations of the planted model | #{inspect(r.text.planted_verdicts)} |
    | gate verdict, the same model with random weights | #{inspect(r.text.random_verdicts)} |

    Sample (temperature 1): `#{String.replace(r.text.sample, "\n", "⏎")}`

    It is text with the statistics of Portuguese, not Portuguese: the gate says `:structured` (more
    structure than every noise control, less than all real text), and that is what it should say.

    ## 3. Any-to-any: every route of the hub, on held-out inputs

    Colour pairs never seen in any fit, new variants (jitter, lighting, sensor
    noise), new phases and amplitudes, noise at 10 dB.

    | route | what it measures | check | value | control | threshold | ok |
    |---|---|---|---|---|---|---|
    #{Enum.map_join(r.any_to_any, "\n", fn rt -> Enum.map_join(rt.checks, "\n", fn c -> "| #{rt.route} | #{rt.measures} | #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end) end)}

    ## 4. Model merging

    A Portuguese specialist (A) and an English one (B), planted bigrams; bits/character on
    held-out text of each domain (lower is better).
    Specialists: A@pt #{f(r.merge.specialists.pt.pt)}, A@en #{f(r.merge.specialists.pt.en)}, B@pt #{f(r.merge.specialists.en.pt)}, B@en #{f(r.merge.specialists.en.en)}.

    | method | pt | en | mean | ms | receipt |
    |---|---|---|---|---|---|
    #{Enum.map_join(r.merge.methods, "\n", fn m -> "| #{m.method} | #{f(m.pt)} | #{f(m.en)} | #{f(m.mean)} | #{m.ms} | #{ok(m.receipt_ok)} |" end)}

    #{Enum.map_join(r.merge.checks, "\n", fn c -> "- #{ok(c.pass)} #{c.name}" end)}

    TIES and DARE presuppose sparse task vectors (small differences from a fine-tune);
    the differences between log-probability tables of two domains are dense, and pruning
    distorts them — measured here, not presumed.

    #{merge_real(Map.get(r, :merge_real))}

    #{real(Map.get(r, :real))}

    ## 5. Substrates

    #{if r.substrates.programs == [], do: "No native worker in this run (oracle only).", else: Enum.map_join(r.substrates.programs, "\n", fn p -> "- #{ok(p.bit_identical)} #{p.program}: native = oracle bit for bit" end)}

    #{round06(Map.get(r, :round06))}

    #{round07(Map.get(r, :round07))}

    #{round08(Map.get(r, :round08))}
    #{round09(Map.get(r, :round09))}
    #{round10(Map.get(r, :round10))}
    #{round11(Map.get(r, :round11))}
    #{round12(Map.get(r, :round12))}
    #{round13(Map.get(r, :round13))}
    #{round14(Map.get(r, :round14))}
    #{round15(Map.get(r, :round15))}
    #{round16(Map.get(r, :round16))}
    #{round17(Map.get(r, :round17))}

    ## 6. Cost of the airlock

    | adapter | family | contract | admit (µs) | build (µs) | lower (µs) | nodes |
    |---|---|---|---|---|---|---|
    #{Enum.map_join(r.lock, "\n", fn l -> "| #{l.adapter} | #{l.family} | #{l.interface} | #{l.admit_us} | #{l.build_us} | #{l.lower_us} | #{l.nodes} |" end)}

    ## Timings (ms)

    #{r.timings_ms |> Enum.sort() |> Enum.map_join(" · ", fn {k, t} -> "#{k} #{t}" end)}
    """
    |> String.replace(~r/\n {4}/, "\n")
  end

  defp round06(nil), do: ""

  defp round06(x) do
    """
    ## 5b. Round 0.6 — experts, latent cache, windows, ÷, convolution, log, state, tree

    Each feature of round 0.6 against its truth **and** against a control that shows that the
    check discriminates (the naive form, the wrong form, the tampered input).

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round07(nil), do: ""

  defp round07(x) do
    """
    ## 5c. Round 0.7 — the office scan, patterns in the output, merging on disk

    The whole path of a scanned page (PDF → CCITT → reading order → reader → language
    model), the formats and patterns of constrained output and *streaming* merging, each against the
    control that the naive form would produce.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round08(nil), do: ""

  defp round08(x) do
    """
    ## 5d. Round 0.8 — tables, JBIG2, resident GPU, sparse experts, Mamba-2, dossier, cluster

    Structure and text of scanned tables (against the 0.7 reading and free reading), the JBIG2
    decoder against jbig2dec, the resident GPU session against the CPU, the predicated 4-bit
    experts against the dense ones, Mamba-2 against the logits of transformers itself, the audit
    dossier against tampering and the *shards* across BEAM nodes against a single node.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round17(nil), do: ""

  defp round17(x) do
    """
    ## 5m. Round 0.17 — the seal, integer programs, causes, the mould, palingenesis, recommendations

    Each claim of the round next to the control that would expose it: the seal that counts off-heap
    binaries against the 0.16 cap that let them through; branch and bound against brute force, and the
    rounded relaxation; a forged optimum against the naive check; identified estimands against the true
    intervention, and the naive P(y | x); a hedge against two models that agree on what is observed and not on
    the effect; a hidden trigger found by SAT against random simulation; a plank that restores the ship
    against a sham of the same norm, under and over the brake; a permuted block against a random change;
    planted interactions against unstructured ratings; one-sided Jacobi against the Gram matrix.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round16(nil), do: ""

  defp round16(x) do
    """
    ## 5l. Round 0.16 — the Majlis, the Dīwān, the Khazāna and Almizan

    The round that took out of the product what was only for show measures what stayed. The khazāna that reopens at the
    old root or the new one after a cut at any byte, against the single file overwritten in place
    (which reads as v2 with a torn value: worse than lost); the fork that copies nothing against the deep
    copy; the hashed export that refuses one changed character against the Markdown that does not see it;
    the context that keeps the pinned instruction against truncation from the tail; conservation decided
    exactly against sampling fooled by a damping of 10⁻⁹; the two projections of Almizan
    against the transliteration that merges names; SHA-256 against the abjad; Fisher–Rao against KL; the natural
    gradient against the plain one; the jail against the local session; the entropy boundary against an injected
    draw.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round15(nil), do: ""

  defp round15(x) do
    """
    ## 5k. Round 0.15 — the Opus: Amalgam, Cupel, Rebis, Aludel, Tabula

    Every piece of the round decides something, so every control asks: *would it have said the same if the
    claim were false?* The exact sum against the left-to-right sum; the flipped bit
    against the bit below the envelope (stated, not faked); conforming summers that cannot be
    accused against the forger who knows the seed; the trojan horse against the random
    simulation that does not see it; the multiplier against the wrong partial product; AES-GCM against
    OpenSSL and the tampered tag; GHZ against independent Hadamards; Motzkin + 1/1000 against
    Motzkin, which touches zero; the barrier against the unstable field; the contract against its
    precedences; the aligned merge against the naive one.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round14(nil), do: ""

  defp round14(x) do
    """
    ## 5j. Round 0.14 — the open workbench: Alembic, Athanor, Touchstone, Crucible, Assay

    The workbench accepts arbitrary input, so every control asks the question that matters for open
    input: *would the same answer have come out if there were nothing to find?* The furnace against
    random search with the same budget; the enumeration against an independent brute force and a
    forged certificate; the proof of R(3,3) against the pentagon; the planted momentum against the random
    walk on the validation set; the same seed against another; the memory bomb against a
    small program; random Hamiltonians rediscovered against dissipative systems with no law;
    the oscillator against the box that is too small; Yoshida against RK4; H₂ against its stretching
    (RHF's known failure, shown); the phylogeny and the regression against the shuffled version; the paired
    test on the null against the planted effect; the calibrated model against the overconfident one; Krippendorff's
    α against random labels; the scaling law against shuffled losses (which exposed an
    `exp` overflow, fixed); the solved game against chance; the browser's noise against the
    server's.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round13(nil), do: ""

  defp round13(x) do
    """
    ## 5i. Round 0.13 — finance, the trading desk and the pending items closed

    Each answer against its reference and against its control: the calendar by the computus against
    the fixed holidays alone; the exact allocation against binary rounding that loses a cent; DI1
    in business days against calendar days; parity and the Greeks against a price below
    intrinsic; the American against the European; the calm smile against Vogt's slice; the bits of the
    oracle and of two threads against the forgotten Itô term; historical VaR against the normal one on
    fat tails (and the size of the test); the planted signal against the best of thirty noises and the
    peek at tomorrow; the Farkas certificate against the wrong proposal; the butterfly that pays against
    the state prices; the engine against the forged journal; the refusal with a cause against the refusal without
    a cause; Hawkes against Poisson; the session against another seed; the signature against the
    rewritten manifest; the affine reading against the compound unit.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round12(nil), do: ""

  defp round12(x) do
    """
    ## 5h. Round 0.12 — workbench, engineering, logic, boards, proteins, render, scene direction

    Each solver against the closed form, the published value or the oracle, and against its control:
    Dormand–Prince against fixed-step RK4; Crank–Nicolson (order 2) against implicit Euler (order 1);
    the system with coherent units against the same with a force in place of a velocity; the optimal
    can with bounds against the divergence without them; trapezoids against Euler on the RC; Newton against
    Gauss–Seidel; ten elements against one; QM6 against the Q4 that locks; invariants against a species
    that is not conserved; Fenske against reflux below the minimum; the whole DRUP proof against the
    truncated one; Knuth–Bendix against the axioms merely oriented; Thales against the false variant; the right
    proposal against the swapped one; perft against the published numbers; CFR+ against uniform play; the
    planned alignment against the shuffled one; the furnace against the biased estimator; and direction
    with names against the sentence with no one.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round11(nil), do: ""

  defp round11(x) do
    """
    ## 5g. Round 0.11 — discovery, mathematics, science, self-play, living scene, sketch, archives

    Sorting networks against randomly drawn and pruned networks; the bit trick against the naive formula
    that overflows; rank 7 against the impossible rank 6; theorems against their false twins;
    conjectures against the trivial triples; homology over ℚ against that over GF(2); the loop against the
    blob; each science experiment against its closed form or the published value and its
    control; the trained agent against the same search without training; the policy of many worlds against that
    of one; the scene, the skeleton, the direction, the sketch and the floor plan against the truth they were
    drawn with; and the archive against one changed byte.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round10(nil), do: ""

  defp round10(x) do
    """
    ## 5f. Round 0.10 — substrate airlock, training, endless context, physics, networks, figures, formulas, CJK, Arabic

    The airlock against a device that rounds operands to bf16; the model vapor trained against
    Witten–Bell and against its own text, shuffled; the endless stream against growing positions; the
    simulator against the pendulum's exact period and against itself on another substrate; the identification
    of the twin against time-shuffled measurements; the policy against the null policy; the alarm against
    the absence of a fault; the networks against their nulls; the charts against permuted labels (which must
    be refused); the formulas against flat reading; CJK against random characters; Arabic
    against the Latin reader.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp round09(nil), do: ""

  defp round09(x) do
    """
    ## 5e. Round 0.9 — studio: diffusion, determinism and cache, upscaling, RL, 3D, audio, MCP

    The Stable Diffusion pipeline against diffusers' own (tiny checkpoint included), the
    studio against itself (stable Merkle root, a cache that recomputes only what changed), the consistent
    upscaler against Lanczos with the same projection, the policies against controls, the mesh against the
    analytic sphere, resampling against decimation and the MCP server against a false root.

    | check | value | control | threshold | ok |
    |---|---|---|---|---|
    #{Enum.map_join(x.checks, "\n", fn c -> "| #{c.name} | #{v(c.value)} | #{v(c.control)} | #{c.threshold} | #{ok(c.pass)} |" end)}
    """
  end

  defp real(nil), do: ""

  defp real(x) do
    o = x.ocr
    tess = fn nil -> "—"; v -> f(v) end

    """
    ## 4c. Real data — reading, speech, handwriting

    Models admitted by the airlock (`priv/ocr`, `priv/speech`, `priv/digits`), data never seen in training.

    | route | measure | vapor | control | Tesseract |
    |---|---|---|---|---|
    | OCR, 5 typefaces outside training (#{o.lines} lines) | CER | #{f(o.cer)} | #{f(o.control_cer)} (wrong fluent text) | #{tess.(o.tesseract_cer)} |
    | OCR, real photo of a page | CER | #{f(o.page.cer)} | — | #{tess.(o.page.tesseract_cer)} |
    | speech, a voice never heard (#{x.speech.clips} recordings) | accuracy | #{f(x.speech.accuracy)} | 0.100 (chance); time-reversed: #{f(x.speech.reversed_accuracy)} | — |
    | handwriting → digit (#{x.digits.held_out} held out) | accuracy | #{f(x.digits.accuracy)} | 0.100 | — |
    | digit → handwriting (#{x.digits.generated} generated), read back | accuracy | #{f(x.digits.read_back_accuracy)} | 0.100 | — |
    | distance to the nearest training image (median) | grey levels | #{f(x.digits.nearest_train.generated)} | held-out real #{f(x.digits.nearest_train.held_out_real)}; memorisation #{f(x.digits.nearest_train.memorising_control)} | — |
    | voice → text → drawing → reading | accuracy | #{f(x.chain.accuracy)} | 0.100 | — |

    CER per typeface: #{o.per_font |> Enum.sort() |> Enum.map_join(", ", fn {k, v} -> "#{k} #{f(v)}" end)}.

    Speech: the held-out voice (chosen before training) is the easiest of the six in the set; holding out each voice in turn (`test/python/train_speech.py --loso`) the mean accuracy is 0.72 ([ANY_TO_ANY.md §6](../ANY_TO_ANY.md)). Reversing the recording in time hardly changes the reading: a spoken digit is recognised by the timbre of its vowels — which is why the control is chance.

    Real page read by vapor:

    ```
    #{o.page.text}
    ```

    #{Enum.map_join(x.checks, "\n", fn c -> "- #{ok(c.pass)} #{c.name}" end)}
    """
  end

  defp merge_real(nil), do: ""

  defp merge_real(m) do
    sec = fn title, part ->
      """
      **#{title}** — diagnosed regime: `#{part.diag.regime}`; chosen on validation: **#{part.chosen}**.

      #{Enum.map_join(part.diag.advice, "\n", &("> " <> &1 <> "  "))}

      | method | validation | pt (test) | en (test) | mean (test) | ms |
      |---|---|---|---|---|---|
      #{Enum.map_join(part.rows, "\n", fn x -> "| #{x.method} | #{f(x.val)} | #{f(x.pt)} | #{f(x.en)} | #{f(x.mean)} | #{x.ms} |" end)}
      """
    end

    """
    ### 4b. Merging trained transformers (not planted)

    Character-level Llama decoders trained by PyTorch (`priv/quality/merge`,
    `test/python/train_merge_models.py`). Bits/character, test disjoint from validation.

    | model | pt | en | mean |
    |---|---|---|---|
    #{m.models |> Enum.sort() |> Enum.map_join("\n", fn {k, s} -> "| #{k} | #{f(s.pt)} | #{f(s.en)} | #{f(s.mean)} |" end)}

    #{sec.("Fine-tunes of one base (ft_pt + ft_en)", m.fine_tune)}

    #{sec.("Trained separately (solo_pt + solo_en, no common base)", m.independent)}

    #{Enum.map_join(m.checks, "\n", fn c -> "- #{ok(c.pass)} #{c.name}" end)}
    """
  end

  defp ok(true), do: "✅"
  defp ok(false), do: "❌"
  defp dir(:up), do: "↑ more structure"
  defp dir(:down), do: "↓ more structure"
  defp f(x) when is_float(x), do: :erlang.float_to_binary(x, decimals: 3)
  defp f(x), do: inspect(x)
  defp e(x) when is_float(x), do: :io_lib.format("~.2e", [x]) |> to_string()
  # tiny nonzero measurements in scientific notation (0.000 would hide them)
  defp v(x) when is_float(x) and x != 0.0 and abs(x) < 1.0e-3, do: e(x)
  # and huge ones (an integrator that blew up) too
  defp v(x) when is_float(x) and abs(x) >= 1.0e9, do: e(x)
  defp v(x) when is_float(x), do: f(x)
  defp v(x) when is_binary(x), do: x
  defp v(nil), do: "—"
  defp v(x) when is_list(x), do: x |> Enum.frequencies() |> Enum.map_join(", ", fn {k, n} -> "#{n}× #{k}" end)
  defp v(x) when is_tuple(x), do: x |> Tuple.to_list() |> Enum.map_join(" / ", &v/1)
  defp v(x), do: inspect(x)

  defp controls(cs), do: Enum.map_join(cs, "; ", fn {k, s} -> "#{k}: #{f(s[:min])}…#{f(s[:max])}" end)
end
