# GENERATED by `lake exe vapor-extract` from proofs/Vapor/*.lean — do not edit.
# lean-source-fnv1a64: a9abbd9c45e86635
defmodule Vapor.Extracted do
  @moduledoc """
  Definitions extracted from the Lean 4 development in `proofs/` (see
  `proofs/Extract.lean`). Each function is the elaborated Lean term that the
  cited theorems are about, printed as Elixir; the conformance suite
  `test/vapor/extracted_conformance_test.exs` holds values computed by Lean.
  Nested pairs follow Lean's `α × β × γ = α × (β × γ)`: `{a, {b, {c, d}}}`.
  """

  @doc "FNV-1a/64 of the Lean sources this module was extracted from."
  def source_digest, do: "a9abbd9c45e86635"

  @doc """
  Register-allocation checker. Sound by `Vapor.RegAlloc.checkAlloc_sound`: an accepted
  assignment is aligned, in range, avoids reserved registers, and never maps two
  simultaneously-live values to a common register.

  Extracted from `Vapor.RegAlloc.checkAlloc`.
  """
  def check_alloc(count_0, reserved_1, ps_2) do
    (Enum.all?(ps_2, fn eta_0 -> placed(count_0, reserved_1, eta_0) end) and pairwise_ok(ps_2))
  end

  @doc """
  Counted no-wrap test `k·a·b < 2³¹`. By `Vapor.integer_parity`, admissible int8
  contractions are bit-identical on every substrate in every accumulation order;
  by `Vapor.admissible_mono` certifying at the maximal extent covers all smaller ones.

  Extracted from `Vapor.admissible`.
  """
  def admissible(k_3, a_4, b_5) do
    (((k_3 * a_4) * b_5) < 2147483648)
  end

  @doc """
  Two's-complement reading of the low 32 bits (`Vapor.wrapS32_of_small`,
  `Vapor.wrapS32_wrap32`).

  Extracted from `Vapor.wrapS32`.
  """
  def wrap_s32(x_6) do
    (if (int_emod(x_6, 4294967296) < 2147483648), do: int_emod(x_6, 4294967296), else: (int_emod(x_6, 4294967296) - 4294967296))
  end

  @doc """
  Minimal coprime pad for 2ᵐ banks: sufficient by `Vapor.padStride_coprime`,
  minimal by `Vapor.padStride_minimal`, conflict-free by `Vapor.conflict_free`.

  Extracted from `Vapor.padStride`.
  """
  def pad_stride(s_7, m_8) do
    (if (m_8 == 0), do: 0, else: (if (nat_mod(s_7, 2) == 0), do: 1, else: 0))
  end

  @doc """
  Bank touched by a lane (`Vapor.bank_injective`).

  Extracted from `Vapor.bankOf`.
  """
  def bank_of(stride_9, lane_10, banks_11) do
    nat_mod((stride_9 * lane_10), banks_11)
  end

  @doc """
  Affine SSM composition, associative with neutral {1, 0} (`Vapor.affineOp_assoc`,
  `Vapor.affineOp_apply`).

  Extracted from `Vapor.affineOp`.
  """
  def affine_op(x_12, y_13) do
    {(elem(y_13, 0) * elem(x_12, 0)), ((elem(y_13, 0) * elem(x_12, 1)) + elem(y_13, 1))}
  end

  @doc """
  Segmented affine combine for ragged batches; a monoid by `Vapor.segAffine_monoid`.

  Extracted from `Vapor.segAffine`.
  """
  def seg_affine(x_14, y_15) do
    {(if (elem(y_15, 1) == true), do: elem(y_15, 0), else: affine_op(elem(x_14, 0), elem(y_15, 0))), (elem(x_14, 1) or elem(y_15, 1))}
  end

  @doc """
  Value of a finite binary32 pattern in units of 2⁻¹⁴⁹ — the model under which
  `Vapor.Binary32.mul_one_unique`, `add_negZero_unique`, `sub_posZero_unique` prove the
  rewriter's rules bit-exact and `add_posZero_refuted` refutes `x + (+0) → x`.

  Extracted from `Vapor.Binary32.units`.
  """
  def units(b_16) do
    (if (sgn(b_16) == 1), do: (-mag(b_16)), else: mag(b_16))
  end

  @doc """
  Exact Wilkinson envelope decision `d ≤ γₙ·s + a` as `d·(2²⁴ − n) ≤ n·s + a·(2²⁴ − n)`,
  monotone in the extent (`Vapor.withinEnvelope_mono`) and in `s`, `a`.

  Extracted from `Vapor.withinEnvelope`.
  """
  def within_envelope(d_17, s_18, a_19, n_20) do
    ((n_20 < inv_unit_roundoff()) and ((d_17 * max(inv_unit_roundoff() - n_20, 0)) <= ((n_20 * s_18) + (a_19 * max(inv_unit_roundoff() - n_20, 0)))))
  end

  @doc false
  def placed(count_21, reserved_22, p_23) do
    (((((0 < elem(elem(elem(p_23, 1), 1), 1)) and (nat_mod(elem(elem(elem(p_23, 1), 1), 0), elem(elem(elem(p_23, 1), 1), 1)) == 0)) and ((elem(elem(elem(p_23, 1), 1), 0) + elem(elem(elem(p_23, 1), 1), 1)) <= count_21)) and (elem(p_23, 0) < elem(elem(p_23, 1), 0))) and Enum.all?(range_list(elem(elem(elem(p_23, 1), 1), 1)), fn k_24 -> (not Enum.member?(reserved_22, (elem(elem(elem(p_23, 1), 1), 0) + k_24))) end))
  end

  @doc false
  def pairwise_ok(ps_25) do
    elem(List.foldr(ps_25, {[], true}, fn p_26, acc_27 -> {[p_26 | elem(acc_27, 0)], (elem(acc_27, 1) and Enum.all?(elem(acc_27, 0), fn eta_0 -> compatible(p_26, eta_0) end))} end), 1)
  end

  @doc false
  def sgn(b_28) do
    nat_div(b_28, 2147483648)
  end

  @doc false
  def mag(b_29) do
    (if (ex(b_29) == 0), do: man(b_29), else: ((man(b_29) + 8388608) * Integer.pow(2, max(ex(b_29) - 1, 0))))
  end

  @doc false
  def inv_unit_roundoff() do
    16777216
  end

  @doc false
  def compatible(p_30, q_31) do
    ((not overlaps(p_30, q_31)) or disjoint(p_30, q_31))
  end

  @doc false
  def ex(b_32) do
    nat_mod(nat_div(b_32, 8388608), 256)
  end

  @doc false
  def man(b_33) do
    nat_mod(b_33, 8388608)
  end

  @doc false
  def overlaps(p_34, q_35) do
    ((elem(p_34, 0) < elem(elem(q_35, 1), 0)) and (elem(q_35, 0) < elem(elem(p_34, 1), 0)))
  end

  @doc false
  def disjoint(p_36, q_37) do
    (((elem(elem(elem(p_36, 1), 1), 0) + elem(elem(elem(p_36, 1), 1), 1)) <= elem(elem(elem(q_37, 1), 1), 0)) or ((elem(elem(elem(q_37, 1), 1), 0) + elem(elem(elem(q_37, 1), 1), 1)) <= elem(elem(elem(p_36, 1), 1), 0)))
  end

  # Lean: n / 0 = 0
  defp nat_div(_a, 0), do: 0
  defp nat_div(a, b), do: div(a, b)
  defp range_list(n), do: Enum.to_list(0..(n - 1)//1)
  # Lean: n % 0 = n
  defp nat_mod(a, 0), do: a
  defp nat_mod(a, b), do: rem(a, b)
  # Lean: Int.emod (Euclidean), a % 0 = a
  defp int_emod(a, 0), do: a
  defp int_emod(a, b), do: Integer.mod(a, abs(b))
end
